apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ccv-pubs-front
  labels:
    app: ccv-pubs-front
  annotations:
    kubernetes.io/ingress.class: proddmz
spec:
  tls:
    - hosts:
      - publications.ccv.brown.edu
      secretName: ccv-pubs-front-tls
  rules:
    - host: publications.ccv.brown.edu
      http:
        paths:
          - path: /
            backend:
              serviceName: ccv-pubs-front
              servicePort: 80