apiVersion: v1
kind: Service
metadata:
  name: ccv-pubs-front
  labels:
    app: ccv-pubs-front
spec:
  type: ClusterIP
  selector:
    app: ccv-pubs-front
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
